services:
  nginx:
    build:
      context: ./nginx-docker
    ports:
      - "8080:8080"
    environment:
      - NEXTJS_CONTAINER_IP=frontend
      - ACTIX_CONTAINER_IP=backend
      - CONF_FILE=dev-nginx.conf
    command: [ 'sh', '/etc/nginx/convert-nginx.sh'] 

  backend:
    container_name: zyenyo-backend
    build:
      context: zyenyo-backend
      target: development
    env_file: .env

  frontend:
    build:
      context: ./zyenyo-frontend
      target: development
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./zyenyo-frontend:/app
      - /app/node_modules
      - /app/.next

  discord:
    build:
      context: ./zyenyo-discord
      target: runner
    env_file: .env
