services:
  nginx:
    build:
      context: ./nginx-docker
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NEXTJS_CONTAINER_IP=frontend
      - ACTIX_CONTAINER_IP=backend
      - CONF_FILE=prod-nginx.conf
    command: [ 'sh', '/etc/nginx/convert-nginx.sh'] 
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  backend:
    container_name: backend
    build:
      context: zyenyo-backend
      target: production
    restart: always
    env_file: .env
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./zyenyo-frontend
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  discord:
    build:
      context: ./zyenyo-discord
      target: runner
    restart: always
    env_file: .env

networks:
  app-network:
    driver: bridge
