services:
  nginx:
    build:
      context: ./nginx-docker
    ports:
      - "80:8080"
    environment:
      - NEXTJS_CONTAINER_IP=frontend
      - ACTIX_CONTAINER_IP=backend
      - CONF_FILE=prod-nginx.conf
    command: [ 'sh', '/etc/nginx/convert-nginx.sh'] 
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"


  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  backend:
    container_name: zyenyo-backend
    build:
      context: zyenyo-backend
      target: production
    restart: always
    env_file: .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./zyenyo-frontend
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "80:8080"

  discord:
    build:
      context: ./zyenyo-discord
      target: runner
    restart: always
    env_file: .env
